-- ═══════════════════════════════════════════════════════════════════════════
--  Kopi Nusantara — Tabel `products` untuk CRUD produk via dashboard admin.
--  Cara pakai: Supabase → SQL Editor → tempel semua → Run. Aman diulang.
--  Selama tabel ini BELUM dibuat, situs otomatis memakai data statik
--  (menu-data.js) — jadi tidak ada yang rusak bila Anda menundanya.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists products (
  id            bigint generated by default as identity primary key,
  name          text    not null,
  description   text,
  price         integer not null check (price >= 0),
  category_id   integer,
  category_name text,
  category_slug text,
  category_icon text,
  image_url     text,
  is_available  boolean not null default true,
  is_featured   boolean not null default false,
  created_at    timestamptz default now()
);

create index if not exists idx_products_category on products(category_slug);

-- Seed 15 produk awal (sama dengan menu saat ini). `on conflict do nothing`
-- membuat perintah ini aman dijalankan berulang tanpa menggandakan data.
insert into products (id, name, description, price, category_id, category_name, category_slug, category_icon, image_url, is_available, is_featured) values
(1,  'Espresso',            'Shot espresso murni dari biji arabika pilihan Flores, dengan crema tebal dan rasa yang bold.',     25000, 1, 'Kopi',     'kopi',     '☕', 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=800&q=80', true, false),
(2,  'Americano',           'Espresso yang diencerkan dengan air panas, menghasilkan rasa kopi yang bersih dan segar.',         28000, 1, 'Kopi',     'kopi',     '☕', 'https://images.unsplash.com/photo-1551030173-122aabc4489c?auto=format&fit=crop&w=800&q=80', true, false),
(3,  'Cappuccino',          'Perpaduan sempurna espresso, susu kukus, dan foam susu yang lembut. Klasik tak lekang waktu.',     35000, 1, 'Kopi',     'kopi',     '☕', 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=800&q=80', true, true),
(4,  'Latte',               'Espresso lembut berpadu susu kukus creamy. Pilihan sempurna untuk hari yang santai.',              38000, 1, 'Kopi',     'kopi',     '☕', 'https://images.unsplash.com/photo-1561882468-9110e03e0f78?auto=format&fit=crop&w=800&q=80', true, true),
(5,  'Cold Brew',           'Kopi diseduh dingin selama 18 jam. Rasa yang smooth, manis alami, tanpa rasa pahit.',              42000, 1, 'Kopi',     'kopi',     '☕', 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80', true, true),
(6,  'V60 Manual Brew',     'Diseduh manual dengan metode pour-over V60. Nikmati kompleksitas rasa single origin kami.',        45000, 1, 'Kopi',     'kopi',     '☕', 'https://images.unsplash.com/photo-1510972527921-ce03766a1cf1?auto=format&fit=crop&w=800&q=80', true, false),
(7,  'Kopi Susu Gula Aren', 'Espresso segar bertemu susu segar dan manisnya gula aren nusantara. Favorit pelanggan kami.',      32000, 1, 'Kopi',     'kopi',     '☕', 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80', true, true),
(8,  'Matcha Latte',        'Matcha premium asal Jepang dipadukan susu oat yang creamy. Sehat dan memanjakan.',                 38000, 2, 'Non-Kopi', 'non-kopi', '🍵', 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80', true, true),
(9,  'Hot Chocolate',       'Cokelat Belgia murni yang kaya, hangat, dan menghibur di setiap tegukan.',                         32000, 2, 'Non-Kopi', 'non-kopi', '🍵', 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=800&q=80', true, false),
(10, 'Lemon Tea Honey',     'Teh hijau segar dengan perasan lemon dan madu asli. Menyegarkan jiwa dan raga.',                   25000, 2, 'Non-Kopi', 'non-kopi', '🍵', 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80', true, false),
(11, 'Strawberry Smoothie', 'Strawberry segar diblender dengan yogurt dan madu. Creamy, segar, dan penuh vitamin.',             40000, 2, 'Non-Kopi', 'non-kopi', '🍵', 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80', true, false),
(12, 'Croissant Butter',    'Croissant berlapis mentega pilihan, dipanggang segar setiap pagi hingga kecokelatan sempurna.',   28000, 3, 'Pastry',   'pastry',   '🥐', 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80', true, true),
(13, 'Banana Bread',        'Roti pisang lembut dengan tekstur yang moist, dibuat dari pisang cavendish matang pilihan.',       25000, 3, 'Pastry',   'pastry',   '🥐', 'https://images.unsplash.com/photo-1598373182133-52452f7691ef?auto=format&fit=crop&w=800&q=80', true, false),
(14, 'Japanese Cheesecake', 'Cheesecake lembut ala Jepang, ringan seperti kapas namun kaya rasa keju cream.',                   35000, 3, 'Pastry',   'pastry',   '🥐', 'https://images.unsplash.com/photo-1567171466295-4afa63d45416?auto=format&fit=crop&w=800&q=80', true, true),
(15, 'Choco Muffin',        'Muffin cokelat yang moist dengan chocolate chip melimpah di setiap gigitan.',                     22000, 3, 'Pastry',   'pastry',   '🥐', 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=800&q=80', true, false)
on conflict (id) do nothing;

-- Geser sequence id agar produk baru dari dashboard lanjut dari id terbesar.
select setval(pg_get_serial_sequence('products', 'id'), coalesce((select max(id) from products), 1));
