// ── Data menu in-memory ─────────────────────────────────────────────────────
// Sumber data untuk route handler /api/* (backend menyatu di dalam Next.js,
// sehingga seluruh aplikasi bisa di-deploy hanya di Vercel — tanpa server terpisah).

export const categories = [
  { id: 1, name: 'Kopi',     slug: 'kopi',     icon: '☕' },
  { id: 2, name: 'Non-Kopi', slug: 'non-kopi', icon: '🍵' },
  { id: 3, name: 'Pastry',   slug: 'pastry',   icon: '🥐' },
]

export const products = [
  { id:1,  image_url:'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=800&q=80', name:'Espresso',            description:'Shot espresso murni dari biji arabika pilihan Flores, dengan crema tebal dan rasa yang bold.',     price:25000, category_id:1, category_name:'Kopi',     category_slug:'kopi',     category_icon:'☕', is_available:true, is_featured:false },
  { id:2,  image_url:'https://images.unsplash.com/photo-1551030173-122aabc4489c?auto=format&fit=crop&w=800&q=80', name:'Americano',           description:'Espresso yang diencerkan dengan air panas, menghasilkan rasa kopi yang bersih dan segar.',         price:28000, category_id:1, category_name:'Kopi',     category_slug:'kopi',     category_icon:'☕', is_available:true, is_featured:false },
  { id:3,  image_url:'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=800&q=80', name:'Cappuccino',          description:'Perpaduan sempurna espresso, susu kukus, dan foam susu yang lembut. Klasik tak lekang waktu.',     price:35000, category_id:1, category_name:'Kopi',     category_slug:'kopi',     category_icon:'☕', is_available:true, is_featured:true  },
  { id:4,  image_url:'https://images.unsplash.com/photo-1561882468-9110e03e0f78?auto=format&fit=crop&w=800&q=80', name:'Latte',               description:'Espresso lembut berpadu susu kukus creamy. Pilihan sempurna untuk hari yang santai.',              price:38000, category_id:1, category_name:'Kopi',     category_slug:'kopi',     category_icon:'☕', is_available:true, is_featured:true  },
  { id:5,  image_url:'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80', name:'Cold Brew',           description:'Kopi diseduh dingin selama 18 jam. Rasa yang smooth, manis alami, tanpa rasa pahit.',              price:42000, category_id:1, category_name:'Kopi',     category_slug:'kopi',     category_icon:'☕', is_available:true, is_featured:true  },
  { id:6,  image_url:'https://images.unsplash.com/photo-1510972527921-ce03766a1cf1?auto=format&fit=crop&w=800&q=80', name:'V60 Manual Brew',     description:'Diseduh manual dengan metode pour-over V60. Nikmati kompleksitas rasa single origin kami.',        price:45000, category_id:1, category_name:'Kopi',     category_slug:'kopi',     category_icon:'☕', is_available:true, is_featured:false },
  { id:7,  image_url:'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80', name:'Kopi Susu Gula Aren', description:'Espresso segar bertemu susu segar dan manisnya gula aren nusantara. Favorit pelanggan kami.',      price:32000, category_id:1, category_name:'Kopi',     category_slug:'kopi',     category_icon:'☕', is_available:true, is_featured:true  },
  { id:8,  image_url:'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80', name:'Matcha Latte',        description:'Matcha premium asal Jepang dipadukan susu oat yang creamy. Sehat dan memanjakan.',                 price:38000, category_id:2, category_name:'Non-Kopi', category_slug:'non-kopi', category_icon:'🍵', is_available:true, is_featured:true  },
  { id:9,  image_url:'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=800&q=80', name:'Hot Chocolate',       description:'Cokelat Belgia murni yang kaya, hangat, dan menghibur di setiap tegukan.',                         price:32000, category_id:2, category_name:'Non-Kopi', category_slug:'non-kopi', category_icon:'🍵', is_available:true, is_featured:false },
  { id:10, image_url:'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80', name:'Lemon Tea Honey',     description:'Teh hijau segar dengan perasan lemon dan madu asli. Menyegarkan jiwa dan raga.',                   price:25000, category_id:2, category_name:'Non-Kopi', category_slug:'non-kopi', category_icon:'🍵', is_available:true, is_featured:false },
  { id:11, image_url:'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80', name:'Strawberry Smoothie', description:'Strawberry segar diblender dengan yogurt dan madu. Creamy, segar, dan penuh vitamin.',             price:40000, category_id:2, category_name:'Non-Kopi', category_slug:'non-kopi', category_icon:'🍵', is_available:true, is_featured:false },
  { id:12, image_url:'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80', name:'Croissant Butter',    description:'Croissant berlapis mentega pilihan, dipanggang segar setiap pagi hingga kecokelatan sempurna.',    price:28000, category_id:3, category_name:'Pastry',   category_slug:'pastry',   category_icon:'🥐', is_available:true, is_featured:true  },
  { id:13, image_url:'https://images.unsplash.com/photo-1598373182133-52452f7691ef?auto=format&fit=crop&w=800&q=80', name:'Banana Bread',        description:'Roti pisang lembut dengan tekstur yang moist, dibuat dari pisang cavendish matang pilihan.',       price:25000, category_id:3, category_name:'Pastry',   category_slug:'pastry',   category_icon:'🥐', is_available:true, is_featured:false },
  { id:14, image_url:'https://images.unsplash.com/photo-1567171466295-4afa63d45416?auto=format&fit=crop&w=800&q=80', name:'Japanese Cheesecake', description:'Cheesecake lembut ala Jepang, ringan seperti kapas namun kaya rasa keju cream.',                  price:35000, category_id:3, category_name:'Pastry',   category_slug:'pastry',   category_icon:'🥐', is_available:true, is_featured:true  },
  { id:15, image_url:'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=800&q=80', name:'Choco Muffin',        description:'Muffin cokelat yang moist dengan chocolate chip melimpah di setiap gigitan.',                      price:22000, category_id:3, category_name:'Pastry',   category_slug:'pastry',   category_icon:'🥐', is_available:true, is_featured:false },
]

// Konfigurasi order online (selaras dengan backend Express)
export const DELIVERY_FEE      = 10000
export const FULFILLMENT_TYPES = ['delivery', 'pickup']
// 'online' = lewat Midtrans (QRIS/GoPay/VA/kartu, dipilih di popup), 'cod' = bayar di tempat
export const PAYMENT_METHODS   = ['online', 'cod']
